name: Format MDX and Lint

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout App Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Set up Git to use HTTPS
        run: git remote set-url origin https://github.com/Creit-Tech/xBull-Wallet-Connect.git

      - name: Install App Dependencies
        run: yarn --prefer-offline

      - name: Check MDX
        run: yarn check:mdx

      - name: Build app
        run: yarn build
